# Source: https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/

version: 1
disable_existing_loggers: False
filters:
    allow_info: 
        (): mv_model_main.InfoFilter
formatters:
    simple:
        format: "%(asctime)s - %(name)s - [%(levelname)s] - %(message)s \r\n"
        datefmt: "%m/%d/%Y %H:%M:%S %p "
handlers:
    error_console:
        class: logging.StreamHandler
        level: ERROR
        formatter: simple
        stream: ext://sys.__stderr__

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: simple
        filename: ../logs/error.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        filters: [allow_info]
        formatter: simple
        filename: ../logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [error_console]
        propagate: no

root:
    level: INFO
    handlers: [error_console, error_file_handler, info_file_handler]